name: Check Jitpack Artifact

on:
  push:
    branches:
      - '**'

jobs:
  check-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download Jitpack Artifact
        run: |
          URL="https://jitpack.io/com/github/nbauma109/ecd/enhanced-class-decompiler/${GITHUB_REF##*/}-SNAPSHOT/enhanced-class-decompiler-${GITHUB_REF##*/}-SNAPSHOT.zip"
          curl --location --fail --connect-timeout 300 --max-time 600 "$URL" --output "enhanced-class-decompiler-${GITHUB_REF##*/}-SNAPSHOT.zip"
      - name: Check if the ZIP file is valid
        run: |
          if unzip -tq "enhanced-class-decompiler-${GITHUB_REF##*/}-SNAPSHOT.zip"; then
            echo "The ZIP file is valid."
          else
            echo "The ZIP file is invalid."
            exit 1
          fi
