name: "Update dependabots"

on:
  push:
    branches: [ 'dependabot/**' ]

# Set the access for individual scopes, or use permissions: write-all
permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:

    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Bump')"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup git user
      run: |
         git config --global user.email "action@github.com"
         git config --global user.name "GitHub Action"
    - name: Update Version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         shopt -s globstar
         git log | grep -w Bump | cut -d' ' -f6,8,10 | xargs -n3 sh -c 'sed -bi "s/$1-$2/$1-$3/g" **/MANIFEST.MF **/build.properties' sh
         git commit -a -m "Updated versions in **/MANIFEST.MF **/build.properties"
         git push
       
