name: Update Eclipse p2 (URL + version)

on:
  schedule:
    - cron: "7 5 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  POM_PATH: pom.xml

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find latest Eclipse SimRel and update pom.xml
        id: do_update
        shell: bash
        run: |
          # Be tolerant: don't exit on non-zero, but keep pipefail for visibility
          set -o pipefail

          POM="${POM_PATH:-pom.xml}"
          if [[ ! -f "$POM" ]]; then
            echo "❌ Cannot find $POM"
            exit 1
          fi

          # Try to detect latest SimRel (YYYY-MM). No hard failure if this flakes.
          latest=""
          for i in 1 2 3; do
            html="$(curl -fsSL https://download.eclipse.org/releases/ 2>/dev/null || true)"
            if [[ -n "$html" ]]; then
              latest="$(printf '%s' "$html" \
                | grep -Eo 'href="[0-9]{4}-[0-9]{2}/"' 2>/dev/null \
                | sed -E 's/^href="([0-9]{4}-[0-9]{2})\/"$/\1/' 2>/dev/null \
                | sort -u | sort -r | head -n1 || true)"
            fi
            [[ -n "$latest" ]] && break
            sleep 2
          done

          if [[ -z "$latest" ]]; then
            echo "⚠️  Could not determine latest Eclipse release; skipping updates."
            echo "changed=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          latest_url="https://download.eclipse.org/releases/${latest}/"
          y="${latest%-*}"
          m="${latest#*-}"
          new_version="${y}.${m}.0"

          echo "Latest: $latest"
          echo "New URL: $latest_url"
          echo "New version: $new_version"

          changed=0

          # Update p2 URL everywhere it appears
          current_url="$(grep -Eo 'https://download\.eclipse\.org/releases/[0-9]{4}-[0-9]{2}/' "$POM" 2>/dev/null | head -n1 || true)"
          if [[ "${current_url:-}" != "$latest_url" ]]; then
            esc_url="$(printf '%s' "$latest_url" | sed 's/[\/&]/\\&/g')"
            sed -i -E "s#https://download\.eclipse\.org/releases/[0-9]{4}-[0-9]{2}/#${esc_url}#g" "$POM" || true
            echo "✅ p2 URL -> $latest_url"
            changed=1
          else
            echo "ℹ️ p2 URL already up to date."
          fi

          # Update ONLY the first YYYY.MM.X root-like version to YYYY.MM.0
          current_ver="$(grep -Eo '<version>[0-9]{4}\.[0-9]{2}\.[0-9]+</version>' "$POM" 2>/dev/null | head -n1 | sed -E 's#</?version>##g' || true)"
          if [[ -z "${current_ver:-}" ]]; then
            echo "ℹ️ No YYYY.MM.X <version> found; skipping version bump."
          elif [[ "$current_ver" != "$new_version" ]]; then
            # Replace only the first occurrence (GNU sed's 0,/<pat>/ range)
            sed -i -E "0,/<version>[0-9]{4}\.[0-9]{2}\.[0-9]+<\/version>/{s//<version>${new_version}<\/version>/}" "$POM" || true
            echo "✅ Version -> $new_version"
            changed=1
          else
            echo "ℹ️ Version already up to date."
          fi

          if [[ $changed -eq 1 ]]; then
            {
              echo "changed=true"
              echo "branch=update-eclipse-${latest}"
              echo "latest=${latest}"
              echo "new_url=${latest_url}"
              echo "new_version=${new_version}"
            } >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "ℹ️ No changes necessary."
          fi

      - name: Create Pull Request
        if: steps.do_update.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update Eclipse SimRel to ${{ steps.do_update.outputs.latest }} (p2 URL + version ${{ steps.do_update.outputs.new_version }})"
          title: "Update Eclipse SimRel to ${{ steps.do_update.outputs.latest }}"
          body: |
            - **p2 URL:** `${{ steps.do_update.outputs.new_url }}`
            - **version:** `${{ steps.do_update.outputs.new_version }}`
          branch: ${{ steps.do_update.outputs.branch }}
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
