name: "Increment version"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: false

      - name: Set up git authentication
        run: |
          git config --global url."https://${{ secrets.PAT_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Setup git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Update Version
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          export VERSION=$(grep Bundle-Version org.sf.feeling.decompiler/META-INF/MANIFEST.MF | cut -d: -f2 | xargs)
          export MAJOR=$(echo $VERSION | cut -d. -f1)
          export MINOR=$(echo $VERSION | cut -d. -f2)
          export PATCH=$(echo $VERSION | cut -d. -f3)
          export NEW_PATCH=$(expr $PATCH + 1)
          export NEW_VERSION=$MAJOR.$MINOR.$NEW_PATCH
          chmod u+x ./update-version.sh
          ./update-version.sh $NEW_VERSION
          git commit -a -m "[update version] $VERSION -> $NEW_VERSION"
          git push
          git tag -a $NEW_VERSION -m "$NEW_VERSION"
          git push origin $NEW_VERSION
