name: Upgrade Java 17 → 21 (with PAT)

on:
  workflow_dispatch:

# Les permissions ci-dessous s'appliquent au GITHUB_TOKEN.
# Le push/PR sera fait avec ton PAT (secrets.GH_PAT), qui possède ses propres droits.
permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (no auto-credentials)
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # évite d'utiliser GITHUB_TOKEN pour le push

      - name: Install SDKMAN!
        shell: bash
        run: |
          # Pas de -u (nounset) : l'init SDKMAN utilise des variables non définies au départ
          set -eo pipefail
          export SDKMAN_DIR="$HOME/.sdkman"
          export SDKMAN_CANDIDATES_API="${SDKMAN_CANDIDATES_API:-https://api.sdkman.io/2}"
          curl -s https://get.sdkman.io | bash
          source "$SDKMAN_DIR/bin/sdkman-init.sh"

          # Mode CI non-interactif
          mkdir -p "$SDKMAN_DIR/etc"
          {
            echo "sdkman_auto_answer=true"
            echo "sdkman_selfupdate_enable=false"
          } >> "$SDKMAN_DIR/etc/config"

          sdk version

      - name: Install latest Java 21 (Temurin) via SDKMAN
        id: jdk
        shell: bash
        run: |
          set -eo pipefail
          export SDKMAN_DIR="$HOME/.sdkman"
          export SDKMAN_CANDIDATES_API="${SDKMAN_CANDIDATES_API:-https://api.sdkman.io/2}"
          source "$SDKMAN_DIR/bin/sdkman-init.sh"

          # identifiant le plus récent de la ligne 21 Temurin (ex: 21.0.x-tem)
          CANDIDATE=$(sdk list java \
            | awk '/[[:space:]]21(\.[0-9]+)*-tem[[:space:]]/ {print $NF}' \
            | sed 's/[^[:alnum:].-]//g' \
            | sort -V | tail -n1)

          if [[ -z "${CANDIDATE:-}" ]]; then
            echo "Aucun candidat Java 21 Temurin trouvé via SDKMAN." >&2
            sdk list java | sed -n '1,200p' || true
            exit 1
          fi

          echo "Installing Java ${CANDIDATE}"
          sdk install java "$CANDIDATE"
          sdk default java "$CANDIDATE"
          java -version
          echo "candidate=$CANDIDATE" >> "$GITHUB_OUTPUT"

      - name: Update references from 17 to 21 in XML/YML/SH (including workflows)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob

          # Tous les fichiers suivis par git (y compris .github/workflows/**)
          mapfile -d '' FILES < <(git ls-files -z '*.xml' '*.yml' '*.yaml' '*.sh')
          echo "Fichiers trouvés: ${#FILES[@]}"

          for f in "${FILES[@]}"; do
            # XML (Maven/Toolchains/Release)
            sed -E -i \
              -e 's#(<java\.version>\s*)17(\s*</java\.version>)#\121\2#g' \
              -e 's#(<maven\.compiler\.source>\s*)17(\s*</maven\.compiler\.source>)#\121\2#g' \
              -e 's#(<maven\.compiler\.target>\s*)17(\s*</maven\.compiler\.target>)#\121\2#g' \
              -e 's#(<source>\s*)17(\s*</source>)#\121\2#g' \
              -e 's#(<target>\s*)17(\s*</target>)#\121\2#g' \
              -e 's#(<release>\s*)17(\s*</release>)#\121\2#g' \
              -e 's#(<maven\.toolchain\.java\.version>\s*)17(\s*</maven\.toolchain\.java\.version>)#\121\2#g' \
              "$f"

            # YAML/YML (setup-java, variables…)
            sed -E -i \
              -e 's#(java[_-]?version:\s*["'\''"]?)17(["'\''"]?)#\121\2#gI' \
              -e 's#(java-version:\s*\[)([^]]*?)17([^]]*?\])#\121\3#gI' \
              -e 's#(JAVA_VERSION:\s*["'\''"]?)17(["'\''"]?)#\121\2#g' \
              -e 's#(JDK_VERSION:\s*["'\''"]?)17(["'\''"]?)#\121\2#g' \
              "$f"

            # Scripts shell (variables + SDKMAN)
            sed -E -i \
              -e 's#(JAVA_VERSION=)17\b#\121#g' \
              -e 's#(JDK_VERSION=)17\b#\121#g' \
              -e 's#(sdk\s+install\s+java\s+)17(\S*)#\121\2#g' \
              -e 's#(sdk\s+use\s+java\s+)17(\S*)#\121\2#g' \
              "$f"

            # Gradle
            sed -E -i \
              -e 's#(sourceCompatibility\s*=\s*)17\b#\121#g' \
              -e 's#(targetCompatibility\s*=\s*)17\b#\121#g' \
              -e 's#(java\.toolchain\.languageVersion\s*=\s*JavaLanguageVersion\.of\()\s*17(\))#\121\2#g' \
              "$f"
          done

          git status --porcelain || true

      # Création de PR avec PAT (permet de modifier .github/workflows/**)
      - name: Create Pull Request (with PAT)
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}   # <= ton PAT (repo + workflow)
          commit-message: "chore: upgrade Java references from 17 to 21"
          branch: chore/java-21-upgrade
          title: "Upgrade Java 17 → 21"
          body: |
            - Met à jour les références Java **17 → 21** dans les fichiers *.xml*, *.yml*/*.yaml* et *.sh* (y compris **.github/workflows/**).
            - Installe une version **Java 21 Temurin valide via SDKMAN** (détectée automatiquement).
            - Candidate installé : `${{ steps.jdk.outputs.candidate }}`.
          author: GitHub Actions <actions@github.com>
          committer: GitHub Actions <actions@github.com>
          signoff: false
