name: Update Eclipse p2 (URL + repository id + version)

on:
  schedule:
    - cron: "7 5 * * *"   # daily
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  POM_PATH: pom.xml   # optional: limit URL/id updates to a specific POM (versions still updated repo-wide via update-version.sh)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure scripts are executable
        run: |
          chmod +x ./update-eclipse-p2.sh
          chmod +x ./update-version.sh

      - name: Run updater
        id: updater
        run: ./update-eclipse-p2.sh "${POM_PATH}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update Eclipse SimRel to ${{ steps.updater.outputs.latest }} (p2 URL + repo id + version ${{ steps.updater.outputs.new_version }})"
          title: "Update Eclipse SimRel to ${{ steps.updater.outputs.latest }}"
          body: |
            - **p2 URL/id:** `${{ steps.updater.outputs.new_url }}` / `eclipse-${{ steps.updater.outputs.latest }}`
            - **version:** `${{ steps.updater.outputs.new_version }}`
          branch: ${{ steps.updater.outputs.branch }}
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
