name: Update Eclipse p2 (URL + version)

on:
  schedule:
    - cron: "30 17 * * 0"   # Runs at 17:30, only on Sunday.
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  POM_PATH: pom.xml

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure script is executable
        run: chmod +x ./update-eclipse-p2.sh

      - name: Run updater
        id: updater
        run: ./update-eclipse-p2.sh "${POM_PATH}"

      - name: Create Pull Request
        if: steps.updater.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update Eclipse SimRel to ${{ steps.updater.outputs.latest }} (p2 URL + version ${{ steps.updater.outputs.new_version }})"
          title: "Update Eclipse SimRel to ${{ steps.updater.outputs.latest }}"
          body: |
            - **p2 URL:** `${{ steps.updater.outputs.new_url }}`
            - **version:** `${{ steps.updater.outputs.new_version }}`
          branch: ${{ steps.updater.outputs.branch }}
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
